# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DxinConexionConfiguracion',
            fields=[
                ('id_conexionbd', models.IntegerField(primary_key=True, serialize=False)),
                ('nb_servidor', models.CharField(max_length=200)),
                ('nb_basedatos', models.CharField(max_length=200)),
                ('nu_puerto', models.IntegerField()),
                ('ti_basedatos', models.CharField(max_length=5)),
                ('id_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fh_carga', models.DateField()),
            ],
            options={
                'db_table': 'dxin_conexion_configuracion',
            },
        ),
        migrations.CreateModel(
            name='DxinFiltros',
            fields=[
                ('id_filtro', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_columna', models.CharField(max_length=50)),
                ('sql', models.CharField(max_length=2000)),
                ('valor_defecto', models.CharField(max_length=2000)),
                ('in_defecto', models.CharField(max_length=1)),
                ('fh_carga', models.DateField()),
                ('ti_valor', models.CharField(default='', max_length=5)),
                ('de_columna', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'dxin_filtros',
            },
        ),
        migrations.CreateModel(
            name='DxinIndicadores',
            fields=[
                ('id_indicador', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('de_indicador', models.CharField(max_length=500)),
                ('id_columna', models.CharField(max_length=50)),
                ('ti_formato_numerico', models.CharField(max_length=50)),
                ('fh_carga', models.DateField()),
                ('in_predeterminado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'dxin_indicadores',
            },
        ),
        migrations.CreateModel(
            name='DxinMapasClaves',
            fields=[
                ('id_proyecto', models.CharField(max_length=50)),
                ('id_clave_mapa', models.CharField(max_length=100)),
                ('id_columna', models.CharField(max_length=100)),
                ('fh_carga', models.DateField()),
                ('id_clave', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dxin_mapas_claves',
            },
        ),
        migrations.CreateModel(
            name='DxinProyectos',
            fields=[
                ('id_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('de_proyecto', models.CharField(max_length=200)),
                ('ti_dato_mostrar', models.CharField(blank=True, max_length=5, null=True)),
                ('sql', models.CharField(blank=True, max_length=2000, null=True)),
                ('fh_carga', models.DateField()),
                ('id_conexionbd', models.ForeignKey(db_column='id_conexionbd', on_delete=django.db.models.deletion.DO_NOTHING, to='dbi_client_app.DxinConexionConfiguracion')),
            ],
            options={
                'db_table': 'dxin_proyectos',
            },
        ),
        migrations.CreateModel(
            name='DxinReglas',
            fields=[
                ('id_proyecto', models.CharField(max_length=100)),
                ('id_indicador', models.CharField(max_length=50)),
                ('ti_regla', models.CharField(max_length=5)),
                ('fh_carga', models.DateField()),
                ('id_regla', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dxin_reglas',
            },
        ),
        migrations.CreateModel(
            name='DxinReglasIndicadores',
            fields=[
                ('id_proyecto', models.CharField(max_length=100)),
                ('id_indicador', models.CharField(max_length=50)),
                ('id_regla', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('operador_logico', models.CharField(max_length=2)),
                ('valor_referencia', models.CharField(max_length=20)),
                ('ti_formato_trama', models.CharField(blank=True, max_length=5, null=True)),
                ('ti_formato_activo', models.CharField(blank=True, max_length=5, null=True)),
                ('ti_texto_color', models.CharField(blank=True, max_length=5, null=True)),
                ('fh_carga', models.DateField()),
                ('id_regla_ind', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dxin_reglas_indicadores',
            },
        ),
        migrations.AddField(
            model_name='dxinindicadores',
            name='id_proyecto',
            field=models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='dbi_client_app.DxinProyectos'),
        ),
        migrations.AddField(
            model_name='dxinfiltros',
            name='id_proyecto',
            field=models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='dbi_client_app.DxinProyectos'),
        ),
    ]
