# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=510, null=True)),
                ('codename', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=508, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=400, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=510, null=True)),
                ('name', models.CharField(blank=True, max_length=510, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DxinConexionConfiguracion',
            fields=[
                ('id_conexionbd', models.IntegerField(primary_key=True, serialize=False)),
                ('nb_servidor', models.CharField(max_length=200)),
                ('nb_basedatos', models.CharField(max_length=200)),
                ('nu_puerto', models.IntegerField()),
                ('ti_basedatos', models.CharField(max_length=5)),
                ('id_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fh_carga', models.DateField()),
            ],
            options={
                'db_table': 'dxin_conexion_configuracion',
            },
        ),
        migrations.CreateModel(
            name='DxinFiltros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto_field', models.CharField(db_column='id_proyecto\n', max_length=100)),
                ('id_filtro_field', models.CharField(db_column='id_filtro\n', max_length=50)),
                ('id_columna_field', models.CharField(db_column='id_columna\n', max_length=50)),
                ('sql_field', models.CharField(db_column='sql\n', max_length=2000)),
                ('valor_defecto_field', models.CharField(blank=True, db_column='valor_defecto\n', max_length=2000, null=True)),
                ('in_defecto_field', models.CharField(db_column='in_defecto\n', max_length=1)),
                ('fh_carga', models.DateField()),
            ],
            options={
                'db_table': 'dxin_filtros',
            },
        ),
        migrations.CreateModel(
            name='DxinIndicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto_field', models.CharField(db_column='id_proyecto\n', max_length=50)),
                ('id_indicador_field', models.CharField(db_column='id_indicador\n', max_length=50)),
                ('de_indicador_field', models.CharField(db_column='de_indicador\n', max_length=500)),
                ('id_columna_field', models.CharField(db_column='id_columna\n', max_length=50)),
                ('ti_formato_numerico_field', models.CharField(db_column='ti_formato_numerico\n', max_length=50)),
                ('fh_carga', models.DateField()),
            ],
            options={
                'db_table': 'dxin_indicadores',
            },
        ),
        migrations.CreateModel(
            name='DxinMapasClaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(max_length=50)),
                ('id_clave_mapa', models.CharField(max_length=100)),
                ('id_columna', models.CharField(max_length=100)),
                ('fh_carga_field', models.DateField(db_column='fh_carga\n')),
            ],
            options={
                'db_table': 'dxin_mapas_claves',
            },
        ),
        migrations.CreateModel(
            name='DxinProyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto_field', models.CharField(db_column='id_proyecto\n', max_length=50)),
                ('de_proyecto', models.CharField(max_length=200)),
                ('id_indicador_defecto_field', models.CharField(blank=True, db_column='id_indicador_defecto\n', max_length=50, null=True)),
                ('ti_dato_mostrar_field', models.CharField(blank=True, db_column='ti_dato_mostrar\n', max_length=5, null=True)),
                ('id_conexionbd', models.IntegerField()),
                ('sql_field', models.CharField(blank=True, db_column='sql\n', max_length=200, null=True)),
                ('fh_carga', models.DateField()),
            ],
            options={
                'db_table': 'dxin_proyectos',
            },
        ),
        migrations.CreateModel(
            name='DxinReglas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto_field', models.CharField(db_column='id_proyecto\n', max_length=100)),
                ('id_indicador_field', models.CharField(db_column='id_indicador\n', max_length=50)),
                ('nu_regla_field', models.TextField(db_column='nu_regla\n')),
                ('ti_regla_field', models.CharField(db_column='ti_regla\n', max_length=5)),
                ('fh_carga_field', models.DateField(db_column='fh_carga\n')),
            ],
            options={
                'db_table': 'dxin_reglas',
            },
        ),
        migrations.CreateModel(
            name='DxinReglasIndicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto_field', models.CharField(db_column='id_proyecto\n', max_length=100)),
                ('id_indicador_field', models.CharField(db_column='id_indicador\n', max_length=50)),
                ('nu_regla_field', models.IntegerField(db_column='nu_regla\n')),
                ('orden_field', models.IntegerField(db_column='orden\n')),
                ('operador_logico_field', models.CharField(db_column='operador_logico\n', max_length=2)),
                ('valor_referencia_field', models.CharField(db_column='valor_referencia\n', max_length=20)),
                ('ti_formato_trama_field', models.CharField(blank=True, db_column='ti_formato_trama\n', max_length=5, null=True)),
                ('ti_formato_activo_field', models.CharField(blank=True, db_column='ti_formato_activo\n', max_length=5, null=True)),
                ('ti_texto_color_field', models.CharField(blank=True, db_column='ti_texto_color\n', max_length=5, null=True)),
                ('fh_carga_field', models.DateField(db_column='fh_carga\n')),
            ],
            options={
                'db_table': 'dxin_reglas_indicadores',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dxinmapasclaves',
            unique_together=set([('id_proyecto', 'id_clave_mapa')]),
        ),
    ]
