# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_client_app', '0005_auto_20160706_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxinfiltros',
            name='id_columna_field',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dxinfiltros',
            name='id_filtro_field',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dxinfiltros',
            name='id_proyecto_field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dxinfiltros',
            name='in_defecto_field',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='dxinfiltros',
            name='sql_field',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='dxinfiltros',
            name='valor_defecto_field',
            field=models.CharField(blank=True, default='N', max_length=2000, null=True),
        ),
    ]
