# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_client_app', '0006_auto_20160706_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dxinconexionconfiguracion',
            options={},
        ),
    ]
