# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_client_app', '0008_auto_20160706_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dxinfiltros',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dxinindicadores',
            options={'managed': False},
        ),
    ]
