# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_client_app', '0009_auto_20160706_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dxinfiltros',
            old_name='id_columna_field',
            new_name='id_columna',
        ),
        migrations.RenameField(
            model_name='dxinfiltros',
            old_name='id_filtro_field',
            new_name='id_filtro',
        ),
        migrations.RenameField(
            model_name='dxinfiltros',
            old_name='id_proyecto_field',
            new_name='id_proyecto',
        ),
        migrations.RenameField(
            model_name='dxinfiltros',
            old_name='in_defecto_field',
            new_name='in_defecto',
        ),
        migrations.RenameField(
            model_name='dxinfiltros',
            old_name='sql_field',
            new_name='sql',
        ),
        migrations.RemoveField(
            model_name='dxinfiltros',
            name='valor_defecto_field',
        ),
        migrations.AddField(
            model_name='dxinfiltros',
            name='other',
            field=models.CharField(default='s', max_length=43),
        ),
        migrations.AddField(
            model_name='dxinfiltros',
            name='valor_defecto',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='dxinfiltros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
