# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_client_app', '0010_auto_20160706_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dxinfiltros',
            options={'managed': False},
        ),
    ]
